ALTER TABLE entries ADD COLUMN date TEXT NOT NULL DEFAULT '';
ALTER TABLE entries ADD COLUMN initials TEXT NOT NULL DEFAULT '';
ALTER TABLE entries ADD COLUMN notes TEXT NOT NULL DEFAULT '';
ALTER TABLE entries ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0;

UPDATE entries SET sort_order = id WHERE sort_order = 0;
